idaholab/mastodon

- doc/content.yml
- test/tests/materials/linear_isotropic_elasticity_tensor_soil/layered_soil_test.i
- test/tests/misc/error_unused/tests
[see MOOSE #9791](https://github.com/idaholab/moose/pull/9791)
> Update for changes in MOOSE

- test/tests/materials/linear_isotropic_elasticity_tensor_soil/tests
> fix test spec syntax

- doc/content.yml
- doc/content/manuals/theory/index.md
- doc/website.yml
> Updates for changes to MooseDocs

- doc/content.yml
- doc/content/getting_started/macos.md
- doc/content/getting_started/mastodon.md
- doc/content/getting_started/ubuntu.md
- doc/content/help/faq.md
- doc/website.yml
> Update install instructions

- src/vectorpostprocessors/ResponseHistoryBuilder.C
> Update to ExecFlagEnum

- include/materials/ComputeISoilStress.h
- include/materials/ComputeIsotropicElasticityTensorSoil.h
> Fixup validParams issues 

- test/tests/materials/linear_isotropic_elasticity_tensor_soil/layered_soil_test_elastic.i
- test/tests/materials/linear_isotropic_elasticity_tensor_soil/layered_soil_test_shear.i
> Fix bad input file syntax

- testroot
refs MOOSE #10764 
https://github.com/idaholab/moose/pull/10764
> Use new testroot options

- doc/content.yml
- src/indicators/ShearWaveIndicator.C
Needed to incorporate vector finite elements
Needs to wait for https://github.com/idaholab/moose/pull/10238
Closes #121
> Updates to MooseVariableInterface and variable getter APIs

- README.md
> Update links to documentation.

- doc/config.yml
> Add acronym extension

- include/base/MastodonApp.h
- src/base/MastodonApp.C
- test/include/base/MastodonTestApp.h
- test/include/interfaces/TestLayeredMaterialInterface.h
- test/src/base/MastodonTestApp.C
- test/src/interfaces/TestLayeredMaterialInterface.C
> Update test object to use new registration style from MOOSE 

- examples/ex01/HYS_darendeli.i
- examples/ex02/HYS_GQH.i
- examples/ex03/shear_beam_Isoil_free_field.i
- examples/ex04/2BlockFriction_Isoilunit.i
- test/tests/bcs/nonreflecting_bc/non_reflecting_bc_test.i
- test/tests/bcs/seismic_displacement/seismic_displacement.i
- test/tests/bcs/seismic_force/seismic_force_test_x_y.i
- test/tests/bcs/seismic_force/seismic_force_test_z.i
- test/tests/dirackernels/function_point_force/force_multi_point.i
- test/tests/dirackernels/function_point_force/force_one_point.i
- test/tests/dirackernels/seismic_source/one_seismic_source.i
- test/tests/mastodonblock/combined/mastodon_block_actions.i
- test/tests/mastodonblock/combined/noaction.i
- test/tests/mastodonblock/model/model_dynamic.i
- test/tests/mastodonblock/model/model_static.i
- test/tests/mastodonblock/model/noaction_dynamic.i
- test/tests/mastodonblock/model/noaction_static.i
- test/tests/mastodonblock/outputs/noaction_stress_strain_output.i
- test/tests/mastodonblock/outputs/stress_strain_output.i
- test/tests/materials/isoil/HYS_GQH.i
- test/tests/materials/isoil/HYS_GQH_noaction.i
- test/tests/materials/isoil/HYS_data_file.i
- test/tests/materials/isoil/HYS_data_file_noaction.i
- test/tests/materials/isoil/HYS_pressure_dependent_stiffness.i
- test/tests/materials/isoil/HYS_stiffness_and_strength_pressure_dependency.i
- test/tests/materials/isoil/HYS_stiffness_and_strength_pressure_dependency_noaction.i
- test/tests/materials/isoil/HYS_thin_layer.i
- test/tests/materials/isoil/HYS_thin_layer_noaction.i
- test/tests/materials/linear_isotropic_elasticity_tensor_soil/layered_soil_test_elastic.i
- test/tests/materials/linear_isotropic_elasticity_tensor_soil/layered_soil_test_shear.i
Just ran some search and replace.
refs idaholab/moose#11867
> Fix deprecated usage of old perf log

- doc/moosedocs.py
> Paths in moosedocs.py should be absolute

- include/base/MastodonApp.h
- src/base/MastodonApp.C
- test/include/base/MastodonTestApp.h
- test/src/base/MastodonTestApp.C
> Update to use registerAll

- test/tests/bcs/nonreflecting_bc/tests
- test/tests/bcs/seismic_force/tests
- test/tests/materials/isoil/tests
> Setting relative error and absolute zero on tests

- doc/config.yml
- doc/content/index.md
- doc/content/manuals/include/developer/documentation.md
[MOOSE #12546](https://github.com/idaholab/moose/pull/12546)
> Update for MOOSEDocs API changes

- examples/ex04/2BlockFriction_Isoilunit.i
- src/actions/ISoilAction.C
- test/tests/bcs/nonreflecting_bc/non_reflecting_bc_test.i
- test/tests/bcs/seismic_displacement/seismic_displacement.i
- test/tests/bcs/seismic_force/seismic_force_test_x_y.i
- test/tests/bcs/seismic_force/seismic_force_test_z.i
- test/tests/dirackernels/function_point_force/force_multi_point.i
- test/tests/dirackernels/function_point_force/force_one_point.i
- test/tests/dirackernels/seismic_source/one_seismic_source.i
- test/tests/mastodonblock/combined/mastodon_block_actions.i
- test/tests/mastodonblock/combined/mastodon_block_actions_2D.i
- test/tests/mastodonblock/combined/noaction.i
- test/tests/mastodonblock/combined/noaction_2D.i
- test/tests/mastodonblock/model/model_dynamic.i
- test/tests/mastodonblock/model/model_dynamic_2D.i
- test/tests/mastodonblock/model/model_static.i
- test/tests/mastodonblock/model/noaction_dynamic.i
- test/tests/mastodonblock/model/noaction_dynamic_2D.i
- test/tests/mastodonblock/model/noaction_static.i
- test/tests/mastodonblock/outputs/noaction_stress_strain_output.i
- test/tests/mastodonblock/outputs/stress_strain_output.i
- test/tests/materials/linear_isotropic_elasticity_tensor_soil/layered_soil_test_elastic.i
- test/tests/materials/linear_isotropic_elasticity_tensor_soil/layered_soil_test_shear.i
- test/tests/pra/sub_sub.i
- test/tests/vectorpostprocessors/housner_spectrum_intensity/housner_spectrum_intensity.i
- test/tests/vectorpostprocessors/response_spectra_calculator/response_spectra_calculator.i
closes #181. 
Continuation of moose issue https://github.com/idaholab/moose/issues/12574
> remove unused parameter store_stress_old from input file #181

- test/tests/materials/linear_spring/spring_static.i
> Remove deprecated input parameter

- include/kernels/StressDivergenceSpring.h
> Tensor API changes. 

- test/tests/pra/sub.i
[MOOSE #12751](https://github.com/idaholab/moose/pull/12751)
> Update for changes to stochastic tools module

- src/actions/MastodonModelAction.C
> Update for moose api changes

- doc/content/index.md
- doc/content/news/2018-10.md
This fixes the layout issues reported, the bibliography list not showing up is a MOOSE issue that I am working on.
(refs #3)
> Update column syntax

- test/tests/pra/sub.i
> Updated test to use SamplerTransientMultiApp

- src/materials/ComputeIsolatorDeformation.C
- src/materials/LinearSpring.C
> Changes for deprecated libmesh elem APIs

- include/indicators/ShearWaveIndicator.h
> Update to more const MOOSE APIs

- include/materials/LayeredMaterialInterface.h
- src/materials/ComputeIsotropicElasticityTensorSoil.C
- src/transfers/HazardCurveTransfer.C
> Updated MOOSE API for AD consistency

- doc/config.yml
- doc/content/sqa/requirements_traceability_matrix.md
- doc/content/sqa/verification_and_validation_results_report.md
> Update SQA config and syntax for changes to MOOSE

- doc/config.yml
> Remove link to SQA docs temporarily

- doc/config.yml
- doc/content/getting_started/macos.md
- doc/content/getting_started/ubuntu.md
- doc/content/sqa/index.md
- doc/content/sqa/mastodon_rtm.md
- doc/content/sqa/mastodon_sdd.md
- doc/content/sqa/mastodon_srs.md
- doc/content/sqa/mastodon_stp.md
- doc/content/sqa/mastodon_vvr.md
- doc/content/sqa/requirements_traceability_matrix.md
- doc/content/sqa/software_design_description.md
- doc/content/sqa/software_test_plan.md
- doc/content/sqa/verification_and_validation_results_report.md
This will need a MOOSE submodule update, but I don't have the necessary changes in MOOSE yet.
> Restore SQA documentation

- doc/config.yml
- doc/content/index.md
- doc/content/manuals/include/materials/fp_isolator-theory.md
- doc/content/manuals/include/materials/fv_damper-theory.md
- doc/content/manuals/include/materials/lr_isolator-theory.md
This is a temporary fix so that the website looks okay when we are at SMiRT.
> Temporary fix for the website before SMiRT. Refs #231.

- doc/content/bib/mastodon.bib
- doc/content/manuals/include/bcs/bcs-user.md
- doc/content/manuals/include/contact/thin_layer-theory.md
- doc/content/manuals/include/gravity/gravity-user.md
- doc/content/manuals/include/mesh/meshing-user.md
- doc/content/manuals/include/misc/getting_started-user.md
- doc/content/sqa/mastodon_srs.md
> Remove un-necessary unicode from docs

- src/transfers/HazardCurveTransfer.C
Closes #254 
Necessary when idaholab/moose#14203 is merged
> Updates for enabling bidirectional transfers

- python/mastodonutils/__init__.py
- python/mastodonutils/test/tests
@ssbodda @cbolisetti The FaultTree objects need some work to work with Python3, I gave it a try but don't understand what you are attempting with some of the operations.
> Update for python 3

- doc/config.yml
- doc/content/bib/publications.md
- doc/content/documentation.menu.md
- doc/content/getting_started/installation.md
- doc/content/getting_started/macos_mojave.md
- doc/content/manuals/developer/index.md
- doc/content/manuals/include/developer/development.md
- doc/content/manuals/include/developer/documentation.md
> Reorganizing documentation [WIP]

- doc/content/help/faq.md
> MASTODON FAQ page

- test/tests/pra/tests
> Fix mistake when I merged to devel by accident

- doc/config.yml
> Update config.yml for changes to MooseDocs

- src/transfers/HazardCurveTransfer.C
> Update MASTODON for MOOSE Piecewise function API changes

- test/tests/pra/sub.i
This is for an upcoming change to MOOSE, it will probably until MOOSE has a merge.
> Add sampler to SamplerTransfer object

- test/tests/materials/lr_isolator/tests
> Avoid race conditions in Mastodon tests

- doc/config.yml
- doc/content/manuals/include/bcs/drm-theory.md
> Update to Google for search

- Makefile
> Trival change to get testing restarted

- doc/config.yml
- doc/content/sqa/index.md
- doc/sqa_reports.yml
> Update to use new SQA report tool

- doc/config.yml
This is no longer needed because of changes to MOOSE
(refs #156)
> Remove hidden syntax

- doc/content/getting_started/install_mastodon.md
- doc/content/index.md
- doc/sqa_reports.yml
- test/tests/markers/minimum_element_size/tests
- test/tests/problem/interface_adapt/tests
- test/tests/vectorpostprocessors/housner_spectrum_intensity/tests
- test/tests/vectorpostprocessors/response_history_builder/tests
- test/tests/vectorpostprocessors/response_history_mean/tests
- test/tests/vectorpostprocessors/response_spectra_calculator/tests
Assorted fixes including
- Finalizing the integration of blackbear. Added documentation for installing blackbear with mastodon. 
- Reducing the number of SQA warnings in the SQA status report. Logged user and theory manual, removed duplicate requirements, and added missing requirements. 
- Centered MASTODON logo.
> SQA and other assorted updates. 

- include/kernels/StressDivergenceDamper.h
- include/kernels/StressDivergenceIsolator.h
- include/kernels/StressDivergenceSpring.h
- src/kernels/StressDivergenceDamper.C
- src/kernels/StressDivergenceIsolator.C
- src/kernels/StressDivergenceSpring.C
> Update to uniform ResidualObject APIs

- doc/content/sqa/mastodon_far.md
- doc/sqa_reports.yml
> Add failure analysis report

- Makefile
- doc/config.yml
- doc/sqa_reports.yml
> Improve documentation completeness 

- test/tests/blackbear/concrete_ASR_swelling/asr_confined.i
- test/tests/blackbear/concrete_ASR_swelling/tests
> Update name of concrete thermal moisture model

- doc/content/manuals/include/developer/development.md
- doc/content/manuals/include/developer/documentation.md
- doc/content/sqa/mastodon_cci.md
- doc/content/sqa/mastodon_scs.md
- doc/content/sqa/mastodon_sll.md
- doc/sqa_reports.yml
(refs #367)
@cbolisetti You need to go in and add some content the the scs.md and cci.md files.
> Update SQA documents for changes to MOOSE and PLN4005

- doc/sqa_reports.yml
> Update SQA report config

- src/actions/MastodonModelAction.C
> Fix model action

- doc/content/examples/example11a.md
- doc/content/examples/example14.md
- doc/content/examples/example3b.md
> Fix duplicate MooseDown shortcuts

- include/auxkernels/MaterialRealCMMAux.h
- src/auxkernels/MaterialRealCMMAux.C
> Remove legacy parameter construction

- src/transfers/PiecewiseFunctionTransfer.C
- test/tests/pra/master.i
- test/tests/pra/sub.i
- test/tests/transfers/piecewise_function/from_master.i
- test/tests/transfers/piecewise_function/to_master.i
See https://github.com/idaholab/moose/pull/19676
MOOSE PR will need to be merged first
> Adapt MASTODON to siblings multiapp transfers

- src/transfers/HazardCurveTransfer.C
- test/tests/transfers/hazard_curve_transfer/hazard_curve_master.i
> Remove use of deprecated 'direction' param

- examples/ex06a/psf_grav.i
- examples/ex06b/actual_simulation_isoil.i
- examples/ex06b/stabilize_isoil.i
- examples/ex06c/actual_simulation_lc.i
- examples/ex06c/stabilize_lc.i
> Replace NodalMaxValue

- README.md
Adding @somu15  as author in readme.
> Added Som as author in readme.

- doc/config.yml
> Add content to documentation config

- doc/config.yml
[Devel documentation target is failing](https://civet.inl.gov/job/1367608/) - this change will fix it.
Tagging @cbolisetti for review and merge.
> Add restart_recover.md to documentation config

- src/kernels/StressDivergenceDamper.C
- src/kernels/StressDivergenceIsolator.C
- src/kernels/StressDivergenceSpring.C
> Update to use tagging interface

- Makefile
- doc/config.yml
- src/base/MastodonApp.C
- unit/Makefile
> Add MooseDocs content keys to enable explicit auto linking

- src/materials/ComputeFVDamperElasticity.C
- src/materials/ComputeIsolatorDeformation.C
- src/materials/LinearSpring.C
Refs [idaholab/moose#24373](https://github.com/idaholab/moose/pull/24373)
> Provide explicit arguments for determining nonlinear systems

- Makefile
- doc/config.yml
https://github.com/idaholab/moose/pull/25585
> Rename heat conduction MOOSE module to heat transfer

- doc/content/sqa/mastodon_rtm.md
- doc/sqa_reports.yml
> Fixup deprecated RTM label

- Makefile
- doc/config.yml
- doc/content/examples/example12a.md
- doc/content/examples/example12c.md
- doc/content/manuals/include/materials/intro_materials-theory.md
- doc/content/manuals/include/misc/getting_started-user.md
- doc/content/source/kernels/StressDivergenceIsolator.md
- doc/sqa_reports.yml
- examples/ex05a/StickModel_accel_base.i
- examples/ex05b/beam_constraint.i
- examples/ex09/SSI_Response.i
- examples/ex09/Structure_Response.i
- examples/ex11a/static/3d_beam_static_first_order.i
- examples/ex11a/static/3d_beam_static_second_order.i
- examples/ex11b/3d_beam_static_refine_PP.i
- examples/ex14/basemat_with_isolators_new.i
- examples/ex14/basemat_with_isolators_new_3D.i
- examples/ex14/building_basemat_with_isolators_new.i
- test/tests/blackbear/concrete_ASR_swelling/asr_confined.i
- test/tests/kernels/time_integration/tests
- test/tests/materials/fv_damper/fv_damper_seismic_frame.i
- unit/Makefile
> Update to new MOOSE module name

- examples/ex03a/shear_beam_Isoil_free_field.i
- examples/ex03a/shear_beam_Isoil_free_field_AD.i
- examples/ex03b/shear_beam_Isoil_free_field_explicit.i
- examples/ex06b/stabilize_isoil.i
- examples/ex06c/stabilize_lc.i
- examples/ex09/SSI_Response.i
- examples/ex09/Soil_Response.i
- examples/ex09/Structure_Response.i
- test/tests/materials/fp_isolator/fp_isolator_seismic_PTV.i
- test/tests/materials/fv_damper/fv_damper_axial.i
- test/tests/materials/fv_damper/fv_damper_seismic_frame.i
- test/tests/materials/lr_isolator/lr_isolator_seismic.i
> Remove usage of deprecated params past their removal date
